- name: "[AZURE-PRIVATE] Add Azure Prereqs in Private Mode"
  hosts: localhost
  gather_facts: yes
  vars_files:
    - vault/azure.yml
    - vars/vars-private.yml
  tasks:
    - name: Install Azure Infra Prereqs for Private
      include_tasks: roles/ocp4-cloud-ipi/tasks/azure-infra-private.yml
