---

- name: Create resource group
  azure_rm_resourcegroup:
    name: "{{ azure_resource_group }}"
    location: "{{ azure_location }}"

# TODO: Check if 443/80 and 22643 are needed during the Install
# Assuming that 443/80 yes because they needed for the access to the Apps from outside of the VNet
# (ExpressRoute, etc)
- name: Create Network Security Group for OCP4
  azure_rm_securitygroup:
    resource_group: "{{ azure_vm_resource_group }}"
    name: "{{ azure_nsg_name }}"
    rules:
      - name: apiserver_in
        protocol: Tcp
        access: Allow
        priority: 101
        direction: Inbound
        destination_port_range: 6443
      - name: apps_http
        description: "No public IP Exposed in Private Mode. Only reachable within VNet/Peering or ExpressRoute"
        protocol: Tcp
        access: Allow
        priority: 102
        direction: Inbound
        source_address_prefix: Internet
        destination_port_range: 80
      - name: apps_https
        description: "No public IP Exposed in Private Mode. Only reachable within VNet/Peering or ExpressRoute"
        protocol: Tcp
        access: Allow
        priority: 103
        direction: Inbound
        source_address_prefix: Internet
        destination_port_range: 443
      - name: AllowVnetInbound
        protocol: Tcp
        access: Allow
        priority: 65000
        direction: Outbound
        source_address_prefix: AzureLoadBalancer
        #  Bastion is INSIDE of the VNet. Port 22 is reachable of Any Nay VNet to Vnet in port 65001
        #- name: bootstrap_ssh_in
        #  description: "Only needed during the OCP4 Install for Tshoot Purposes. Delete after"
        #  protocol: Tcp
        #  destination_port_range: 22
        #  access: Allow
        #  priority: 103
        #  direction: Inbound

- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_vnet_name }}"
    address_prefixes: "{{ azure_vnet_cidr }}"

- name: Add subnet for control-plane
  azure_rm_subnet:
    resource_group: "{{ azure_resource_group }}"
    name: control-plane
    address_prefix: "{{ azure_subnet_controlplane }}"
    virtual_network: "{{ azure_vnet_name }}"
    security_group: "{{ azure_nsg_name }}"

- name: Add subnet for compute
  azure_rm_subnet:
    resource_group: "{{ azure_resource_group }}"
    name: compute
    address_prefix: "{{ azure_subnet_compute }}"
    virtual_network: "{{ azure_vnet_name }}"
    security_group: "{{ azure_nsg_name }}"

- name: Add subnet for bastion
  azure_rm_subnet:
    resource_group: "{{ azure_resource_group }}"
    name: bastion
    address_prefix: "{{ azure_subnet_bastion }}"
    virtual_network: "{{ azure_vnet_name }}"

# https://docs.openshift.com/container-platform/4.6/installing/installing_azure/installing-azure-private.html#private-clusters-about-azure_installing-azure-private
# https://github.com/ansible/ansible/issues/64036
- name: Create private dns zone
  azure_rm_resource:
    resource_group: "{{ azure_resource_group }}"
    provider: network
    resource_type: privateDnsZones
    resource_name: "{{ azure_dns_zone }}"
    api_version: "2018-09-01"
    body:
      location: global
    idempotency: yes

# https://docs.microsoft.com/en-us/azure/dns/private-dns-virtual-network-links
# https://docs.microsoft.com/en-us/rest/api/dns/privatedns/virtualnetworklinks/createorupdate
- name: Link private dns to vnet
  azure_rm_resource:
    resource_group: "{{ azure_resource_group }}"
    provider: network
    resource_type: privateDnsZones
    resource_name: "{{ azure_dns_zone }}"
    subresource:
      - type: virtualNetworkLinks
        name: "{{ azure_vnet_name}}_link"
    api_version: "2018-09-01"
    body:
      location: global
      properties:
        virtualNetwork:
          id: "/subscriptions/{{ azure_subscription_id }}/resourceGroups/{{ azure_resource_group }}/providers/Microsoft.Network/virtualNetworks/{{ azure_vnet_name }}"
        registrationEnabled: false
    idempotency: yes
  register: result_link
  retries: 5
  delay: 10
  until: result_link is not failed

# TODO: Add the Security Groups?
# https://docs.openshift.com/container-platform/4.7/installing/installing_azure/installing-azure-private.html#installation-about-custom-azure-vnet-nsg-requirements_installing-azure-private

# TODO2: Adding Virtual Service Endpoint and AzureResourceManager to the Prereqs of the Airgapped
# installation
# TODO3: Adding the Inbound and Outbound from Masters and Workers to the Azure Service Manager API
