---

##### Tasks for a IPI CONNECTED Installation
#- block:
#    - import_tasks: azure-infra.yml
#    - import_tasks: download.yml
#    - import_tasks: create_config.yml
#    - import_tasks: install.yml
#    - import_tasks: print_info.yml
#  when:
#    - cloud == "azure"
#    - mode == "public"

##### Tasks for a IPI PRIVATE/DISCONNECTED Installation

### Private/Disconnected Install of Infrastructure in Azure
- block:
    - import_tasks: azure-infra-private.yml # Azure Vnets / Subnets
    - import_tasks: azure-bastion-infra.yml # Bastion Install
  when:
    - cloud == "azure"
    - mode == "private" or mode == "disconnected"
    - action == "provision-infra"

- block:
    - import_tasks: azure-infra-firewall.yml        # Adding the Azure Firewall
  when:
    - cloud == "azure"
    - mode == "private"
    - egress == "firewall"
    - action == "provision-infra"

### Private/Disconnected Azure Login/Creds and Bastion Packages
- block:
    - import_tasks: bastion-azure-login.yml
    - import_tasks: bastion-packages.yml
  when:
    - cloud == "azure"
    - mode == "private" or mode == "disconnected"
    - action == "prepare-bastion"

### Private Installation using mode=xxx as Outboundtype (default Proxy)
- block:
    - import_tasks: download.yml
    - import_tasks: create-config.yml
  when:
    - cloud == "azure"
    - mode == "private"
    - action == "prepare-bastion"

### Disconnected installation using Mirror Registry
- block:
    - import_tasks: bastion-registry.yml
    - import_tasks: download.yml
    - import_tasks: bastion-mirror.yml
    - import_tasks: create-config.yml
  when:
    - cloud == "azure"
    - mode == "disconnected"
    - action == "prepare-bastion"

### Installation of the Openshift Cluster
- block:
    - import_tasks: install.yml
  when:
    - cloud == "azure"
    - action == "install"
